name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
  
      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Unit test
        run: |
          dotnet test \
            --verbosity normal \
            --logger "html;LogFileName=UnitTests.html" \
            tests/MyInvest.UnitTests

      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests/MyInvest.UnitTests/TestResults/UnitTests.html
          
  integration_test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [ compile ]
    services: 
      postgres:
        image: postgres:14.1
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: 'myinvest-tests'
          POSTGRES_PASSWORD: 'testingdb'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Integration test
        run: |
          dotnet test \
            --verbosity normal \
            --logger "html;LogFileName=IntegrationTests.html" \
            tests/MyInvest.IntegrationTests

      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests/MyInvest.UnitTests/TestResults/IntegrationTests.html
