name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore

  unit_test:
    name: Unit test
    needs: [ compile ]
    uses: ./.github/workflows/callable-run-tests.yml
    with:
      test_suite: UnitTests

  integration_test:
    name: Integration test
    needs: [ compile ]
    uses: ./.github/workflows/callable-run-tests.yml
    with:
      test_suite: IntegrationTests

  component_test:
    name: Component test
    needs: [ compile ]
    uses: ./.github/workflows/callable-run-tests.yml
    with:
      test_suite: ComponentTests

  app_container:
    name: Build & push app container
    if: success() && github.event_name == 'push'
    needs: 
      - unit_test
      - integration_test
      - component_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ghcr.io/lewis-od/my-invest/myinvest:${{ github.run_number }}
  
  migrations_container:
    name: Build & push migrations container
    if: success() && github.event_name == 'push'
    needs:
      - unit_test
      - integration_test
      - component_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./
          file: Dockerfile.migrations
          push: true
          tags: ghcr.io/lewis-od/my-invest/myinvest-migrations:${{ github.run_number }}
