name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [ compile ]
    defaults: 
      run:
        working-directory: tests/MyInvest.UnitTests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
  
      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: dotnet restore --locked-mode
        
      - name: Build project
        run: dotnet build

      - name: Unit test
        run: |
          dotnet test \
            --no-build \
            --verbosity normal \
            --logger "html;LogFileName=UnitTests.html"

      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests/MyInvest.UnitTests/TestResults/UnitTests.html
          
  integration_test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [ compile ]
    defaults:
      run:
        working-directory: tests/MyInvest.IntegrationTests
    services: 
      postgres:
        image: postgres:14.1
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: 'myinvest-tests'
          POSTGRES_PASSWORD: 'testingdb'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore NuGet cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: dotnet restore --locked-mode
        
      - name: Build project
        run: dotnet build

      - name: Integration test
        run: |
          dotnet test \
            --no-build \
            --verbosity normal \
            --logger "html;LogFileName=IntegrationTests.html"

      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests/MyInvest.IntegrationTests/TestResults/IntegrationTests.html
          
  app_container:
    name: Build & push app container
    if: success() && github.event_name == 'push'
    needs: 
      - unit_test
      - integration_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: src/MyInvest
          push: true
          tags: ghcr.io/lewis-od/my-invest/myinvest:${{ github.run_number }}
  
  migrations_container:
    name: Build & push migrations container
    if: success() && github.event_name == 'push'
    needs:
      - unit_test
      - integration_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: src/MyInvest
          file: src/MyInvest/Dockerfile.migrations
          push: true
          tags: ghcr.io/lewis-od/my-invest/myinvest-migrations:${{ github.run_number }}
